"""empty message

Revision ID: 154b2b1f0aaa
Revises: 5e30acbc5b49
Create Date: 2024-07-08 09:15:48.315913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154b2b1f0aaa'
down_revision = '5e30acbc5b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
